{{- if .Values.secrets_enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.values }}
  {{ $key }}: {{ quote $val | b64enc }}
  {{- end}}
{{- end}}